// frontend/src/components/ConversationList.vue
<template>
  <div class="bg-gray-100 rounded-lg overflow-hidden">
    <!-- ヘッダー -->
    <div class="bg-slate-50 px-4 py-2 border-b border-gray-200/60 rounded-t-lg rounded-b-lg mb-4">
      <h2 class="text-xl font-semibold text-gray-800">{{ $t('conversations.title') }}</h2>
      <p class="text-sm text-gray-600 mt-1">
        {{ totalThreads && totalThreads > actualThreads ? $t('conversations.showingThreadsFiltered', { threads: actualThreads.toLocaleString(), messages: actualMessages.toLocaleString(), totalThreads: totalThreads.toLocaleString() }) : $t('conversations.showingThreads', { threads: actualThreads.toLocaleString(), messages: actualMessages.toLocaleString() }) }}
      </p>
    </div>

    <!-- ローディング -->
    <div v-if="loading && conversations.length === 0" class="p-8 text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500 mx-auto"></div>
      <p class="text-gray-500 mt-4">{{ $t('conversations.loading') }}</p>
    </div>

    <!-- 会話がない場合 -->
    <div v-else-if="conversations.length === 0" class="p-8 text-center">
      <div class="text-gray-400 text-6xl mb-4">💬</div>
      <h3 class="text-lg font-medium text-gray-900 mb-2">{{ $t('conversations.noConversations') }}</h3>
      <p class="text-gray-500">{{ $t('conversations.noConversationsHint') }}</p>
    </div>

    <!-- 会話リスト -->
    <div v-else class="space-y-6">
      <div
        v-for="(threadGroup, threadIndex) in groupedConversations"
        :key="`thread-${threadIndex}`"
        class="bg-white rounded-xl p-4 shadow-lg hover:shadow-xl transition-all duration-200"
      >
        <div class="space-y-3">
          <MessageItem
            v-for="(conversation, index) in threadGroup"
            :key="`${conversation.session_id}-${index}`"
            :conversation="conversation"
            :index="index"
            :expanded-items="expandedItems"
            :render-markdown="renderMarkdown"
            :handle-code-copy="handleCodeCopy"
            :should-show-toggle-button="shouldShowToggleButton"
            @toggle-expand="toggleExpand"
          />
        </div>
      </div>
    </div>

    <!-- もっと読み込むボタン -->
    <div v-if="hasMore" class="p-6 bg-transparent border-t border-gray-200/60 rounded-b-lg">
      <div v-if="lastLoadedCount > 0" class="mb-3 text-center text-sm text-green-600 font-medium animate-pulse">
        ✓ {{ $t('conversations.newConversationsLoaded', { count: lastLoadedCount }) }}
      </div>
      <button
        @click="handleLoadMore"
        :disabled="loading"
        class="w-full px-4 py-2 bg-primary-500 text-white rounded-md hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300"
        :class="{ 'animate-pulse': loading }"
      >
        <span v-if="loading" class="flex items-center justify-center">
          <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          {{ $t('conversations.loading') }}
        </span>
        <span v-else>{{ $t('conversations.loadMore') }} {{ loadMoreRangeText }}</span>
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import MarkdownIt from 'markdown-it'
import MessageItem from './MessageItem.vue'

const { t: $t } = useI18n()

const emit = defineEmits(['load-more'])
const props = defineProps({
  conversations: {
    type: Array,
    default: () => []
  },
  loading: {
    type: Boolean,
    default: false
  },
  hasMore: {
    type: Boolean,
    default: false
  },
  totalThreads: {
    type: Number,
    default: 0
  },
  totalMessages: {
    type: Number,
    default: 0
  },
  actualThreads: {
    type: Number,
    default: 0
  },
  actualMessages: {
    type: Number,
    default: 0
  }
})

// Markdownパーサーの初期化
const md = new MarkdownIt({
  html: false,
  xhtmlOut: false,
  breaks: true,
  linkify: true,
  typographer: true
})

// コードブロックのカスタムレンダラー
const originalCodeBlockRender = md.renderer.rules.code_block || md.renderer.rules.fence
md.renderer.rules.code_block = md.renderer.rules.fence = function(tokens, idx, options, env, self) {
  const token = tokens[idx]
  const code = token.content.trim()
  const lang = token.info ? token.info.trim() : ''
  const id = `code-block-${Math.random().toString(36).substr(2, 9)}`

  return `<div class="code-block-container">
    <div class="code-block-header">
      <span class="code-language">${lang || 'text'}</span>
      <button class="copy-button" data-code-id="${id}" title="コピー">
        <svg class="copy-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
        </svg>
        <svg class="check-icon icon-hidden" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polyline points="20,6 9,17 4,12"></polyline>
        </svg>
      </button>
    </div>
    <pre class="code-block-content"><code id="${id}" class="language-${lang}">${md.utils.escapeHtml(code)}</code></pre>
  </div>`
}

// 展開状態管理
const expandedItems = ref(new Set())
const lastLoadedCount = ref(0)

// クリップボードコピー機能
const copyToClipboard = async (codeId) => {
  try {
    const codeElement = document.getElementById(codeId)
    if (!codeElement) return

    const code = codeElement.textContent
    await navigator.clipboard.writeText(code)

    // ボタンのアイコンを一時的に変更
    const button = document.querySelector(`[data-code-id="${codeId}"]`)
    if (button) {
      const copyIcon = button.querySelector('.copy-icon')
      const checkIcon = button.querySelector('.check-icon')

      copyIcon.classList.add('icon-hidden')
      checkIcon.classList.remove('icon-hidden')

      setTimeout(() => {
        copyIcon.classList.remove('icon-hidden')
        checkIcon.classList.add('icon-hidden')
      }, 2000)
    }
  } catch (err) {
    console.error('クリップボードへのコピーに失敗:', err)
  }
}

// 計算プロパティ
const groupedConversations = computed(() => {
  // バックエンドから既にグループ化された配列が返される
  return props.conversations
})

const loadMoreRangeText = computed(() => {
  if (!props.totalThreads || props.actualThreads === 0) return ''

  const start = props.actualThreads + 1
  const defaultBatchSize = 50 // デフォルトの読み込み件数
  const remaining = props.totalThreads - props.actualThreads
  const end = props.actualThreads + Math.min(defaultBatchSize, remaining)

  return $t('conversations.loadMoreThreadRange', { start: start.toLocaleString(), end: end.toLocaleString() })
})

// メソッド
const renderMarkdown = (content, searchKeyword = null) => {
  if (!content) return ''

  // まずMarkdownをレンダリング
  let renderedContent = md.render(content)

  // 検索キーワードがある場合のみ、レンダリング後のHTMLにハイライトを適用
  if (searchKeyword && searchKeyword.trim()) {
    const regex = new RegExp(`(${searchKeyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi')
    renderedContent = renderedContent.replace(regex, '<mark>$1</mark>')
  } else {
    // キーワードがない場合は既存の<mark>タグを除去
    renderedContent = renderedContent.replace(/<mark>(.*?)<\/mark>/gi, '$1')
  }

  return renderedContent
}

const handleLoadMore = () => {
  const prevCount = props.actualThreads
  emit('load-more')

  // 少し待ってから新しく読み込まれた件数を計算
  setTimeout(() => {
    const newCount = props.actualThreads
    lastLoadedCount.value = newCount - prevCount

    // 3秒後にメッセージを非表示
    setTimeout(() => {
      lastLoadedCount.value = 0
    }, 3000)
  }, 500)
}

const toggleExpand = (index) => {
  if (expandedItems.value.has(index)) {
    expandedItems.value.delete(index)
  } else {
    expandedItems.value.add(index)
  }
}

// 「もっと見る」ボタンを表示するかどうかの判定
const shouldShowToggleButton = (content) => {
  // 改行で分割して行数をカウント
  const lines = content.split('\n')
  // 3行以上、または1行が長すぎる場合にボタンを表示
  return lines.length > 3 || content.length > 200
}

// クリックイベントハンドラー
const handleCodeCopy = (event) => {
  const button = event.target.closest('.copy-button')
  if (button) {
    const codeId = button.getAttribute('data-code-id')
    if (codeId) {
      copyToClipboard(codeId)
    }
  }
}
</script>

<style scoped>

/* Markdownコンテンツのスタイリング */
.markdown-content :deep(h1),
.markdown-content :deep(h2),
.markdown-content :deep(h3),
.markdown-content :deep(h4),
.markdown-content :deep(h5),
.markdown-content :deep(h6) {
  @apply font-bold text-gray-900 mb-2 mt-4;
}

.markdown-content :deep(h1) { @apply text-xl; }
.markdown-content :deep(h2) { @apply text-lg; }
.markdown-content :deep(h3) { @apply text-base; }

.markdown-content :deep(p) {
  @apply mb-3 last:mb-0 leading-relaxed;
}

.markdown-content :deep(ul),
.markdown-content :deep(ol) {
  @apply mb-3 pl-6;
}

.markdown-content :deep(li) {
  @apply mb-1;
}

.markdown-content :deep(ul li) {
  @apply list-disc;
}

.markdown-content :deep(ol li) {
  @apply list-decimal;
}

.markdown-content :deep(blockquote) {
  @apply border-l-4 border-gray-300 pl-4 italic text-gray-600 my-3;
}

.markdown-content :deep(code) {
  @apply bg-gray-100 px-1 py-0.5 rounded text-sm font-mono text-gray-800;
}

.markdown-content :deep(pre) {
  @apply bg-gray-100 p-3 rounded-md overflow-x-auto mb-3 border;
}

.markdown-content :deep(pre code) {
  @apply bg-transparent p-0 text-sm;
}

.markdown-content :deep(a) {
  @apply text-blue-600 hover:text-blue-800 underline;
}

.markdown-content :deep(strong) {
  @apply font-bold;
}

.markdown-content :deep(em) {
  @apply italic;
}

.markdown-content :deep(hr) {
  @apply border-gray-300 my-4;
}

.markdown-content :deep(table) {
  @apply w-full border-collapse border border-gray-300 mb-3;
}

.markdown-content :deep(th),
.markdown-content :deep(td) {
  @apply border border-gray-300 px-3 py-2 text-left;
}

.markdown-content :deep(th) {
  @apply bg-gray-50 font-semibold;
}

/* 検索ハイライト */
.markdown-content :deep(mark) {
  @apply bg-yellow-200 px-1 py-0.5 rounded-sm font-medium;
}

/* コードブロックのスタイリング */
.markdown-content :deep(.code-block-container) {
  @apply relative mb-4 rounded-lg overflow-hidden border border-gray-300;
}

.markdown-content :deep(.code-block-header) {
  @apply flex items-center justify-between bg-gray-50 px-3 py-2 border-b border-gray-200;
}

.markdown-content :deep(.code-language) {
  @apply text-sm font-medium text-gray-600;
}

.markdown-content :deep(.copy-button) {
  @apply flex items-center justify-center w-8 h-8 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1 transition-colors duration-200;
}

.markdown-content :deep(.copy-button svg) {
  @apply text-gray-600;
}

.markdown-content :deep(.copy-button:hover svg) {
  @apply text-gray-800;
}

.markdown-content :deep(.code-block-content) {
  @apply m-0 bg-gray-100;
}

.markdown-content :deep(.code-block-content code) {
  @apply block p-4 bg-transparent text-sm font-mono leading-relaxed;
}

.markdown-content :deep(.icon-hidden) {
  display: none;
}
</style>

// frontend-nextjs/components/ConversationList.tsx
'use client';

import { useState, useRef, useCallback } from 'react';
import { useTranslations } from 'next-intl';
import MessageItem from './MessageItem';
import { renderMarkdown, copyToClipboard } from '@/lib/utils/markdown';

interface Message {
  type: 'user' | 'assistant';
  content: string;
  timestamp: string;
  uuid?: string;
  session_id?: string;
  is_search_match?: boolean;
  search_keyword?: string;
}

interface NewMessageManager {
  getDisplayMessages: (group: Message[], groupIndex: number) => Message[];
  hasUnreadMessages: (group: Message[], groupIndex: number) => boolean;
  getUnreadCount: (group: Message[], groupIndex: number) => number;
  showNewMessages: (group: Message[], groupIndex: number) => void;
}

interface ConversationListProps {
  conversations: Message[][];
  loading?: boolean;
  hasMore?: boolean;
  totalThreads?: number;
  totalMessages?: number;
  actualThreads?: number;
  actualMessages?: number;
  newMessageManager?: NewMessageManager | null;
  onLoadMore?: () => void;
  onShowNewMessages?: (params: { group: Message[]; groupIndex: number }) => void;
}

export default function ConversationList({
  conversations = [],
  loading = false,
  hasMore = false,
  totalThreads = 0,
  totalMessages = 0,
  actualThreads = 0,
  actualMessages = 0,
  newMessageManager = null,
  onLoadMore,
  onShowNewMessages,
}: ConversationListProps) {
  const t = useTranslations('conversations');
  const [expandedItems, setExpandedItems] = useState<Set<number>>(new Set());
  const [lastLoadedCount, setLastLoadedCount] = useState(0);

  const toggleExpand = useCallback((index: number) => {
    setExpandedItems((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(index)) {
        newSet.delete(index);
      } else {
        newSet.add(index);
      }
      return newSet;
    });
  }, []);

  const handleCodeCopy = useCallback((event: React.MouseEvent) => {
    const button = (event.target as HTMLElement).closest('.copy-button');
    if (button) {
      const codeId = button.getAttribute('data-code-id');
      if (codeId) {
        copyToClipboard(codeId);
      }
    }
  }, []);

  const shouldShowToggleButton = useCallback((content: string) => {
    // Show button if more than 3 lines or content is too long
    const lines = content.split('\n');
    return lines.length > 3 || content.length > 200;
  }, []);

  const getDisplayMessages = useCallback(
    (group: Message[], groupIndex: number) => {
      if (!newMessageManager || !Array.isArray(group)) {
        return Array.isArray(group) ? group : [];
      }
      return newMessageManager.getDisplayMessages(group, groupIndex);
    },
    [newMessageManager]
  );

  const shouldShowNewMessageButton = useCallback(
    (group: Message[], groupIndex: number) => {
      if (!newMessageManager || !Array.isArray(group)) {
        return false;
      }
      return newMessageManager.hasUnreadMessages(group, groupIndex);
    },
    [newMessageManager]
  );

  const getUnreadMessageCount = useCallback(
    (group: Message[], groupIndex: number) => {
      if (!newMessageManager || !Array.isArray(group)) {
        return 0;
      }
      return newMessageManager.getUnreadCount(group, groupIndex);
    },
    [newMessageManager]
  );

  const showNewMessages = useCallback(
    (group: Message[], groupIndex: number) => {
      onShowNewMessages?.({ group, groupIndex });
    },
    [onShowNewMessages]
  );

  const handleLoadMore = useCallback(() => {
    const prevCount = actualThreads;
    onLoadMore?.();

    // Wait a bit and calculate newly loaded count
    setTimeout(() => {
      const newCount = actualThreads;
      setLastLoadedCount(newCount - prevCount);

      // Hide message after 3 seconds
      setTimeout(() => {
        setLastLoadedCount(0);
      }, 3000);
    }, 500);
  }, [actualThreads, onLoadMore]);

  const loadMoreRangeText = () => {
    if (!totalThreads || actualThreads === 0) return '';

    const start = actualThreads + 1;
    const defaultBatchSize = 50;
    const remaining = totalThreads - actualThreads;
    const end = actualThreads + Math.min(defaultBatchSize, remaining);

    return `(${start.toLocaleString()} - ${end.toLocaleString()})`;
  };

  return (
    <div className="bg-gray-100 rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-slate-50 px-4 py-2 border-b border-gray-200/60 rounded-t-lg rounded-b-lg mb-4">
        <h2 className="text-xl font-semibold text-gray-800">{t('title')}</h2>
        <p className="text-sm text-gray-600 mt-1">
          {totalThreads && totalThreads > actualThreads
            ? t('showingThreadsFiltered', {
                threads: actualThreads.toLocaleString(),
                messages: actualMessages.toLocaleString(),
                totalThreads: totalThreads.toLocaleString()
              })
            : t('showingThreads', {
                threads: actualThreads.toLocaleString(),
                messages: actualMessages.toLocaleString()
              })}
        </p>
      </div>

      {/* Loading */}
      {loading && conversations.length === 0 && (
        <div className="p-8 text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500 mx-auto"></div>
          <p className="text-gray-500 mt-4">{t('loading')}</p>
        </div>
      )}

      {/* No conversations */}
      {!loading && conversations.length === 0 && (
        <div className="p-8 text-center">
          <div className="text-gray-400 text-6xl mb-4">💬</div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">{t('noConversations')}</h3>
          <p className="text-gray-500">{t('noConversationsHint')}</p>
        </div>
      )}

      {/* Conversation list */}
      {conversations.length > 0 && (
        <div className="space-y-6">
          {conversations.map((threadGroup, threadIndex) => (
            <div
              key={`thread-${threadIndex}`}
              className="bg-white rounded-xl p-4 shadow-lg hover:shadow-xl transition-all duration-200"
            >
              <div className="space-y-3">
                {getDisplayMessages(threadGroup, threadIndex).map((conversation, index) => (
                  <MessageItem
                    key={`${conversation.session_id}-${index}`}
                    conversation={conversation}
                    index={Number(index)}
                    expandedItems={expandedItems}
                    renderMarkdown={renderMarkdown}
                    handleCodeCopy={handleCodeCopy}
                    shouldShowToggleButton={shouldShowToggleButton}
                    onToggleExpand={toggleExpand}
                  />
                ))}
              </div>

              {/* Show new messages button */}
              {shouldShowNewMessageButton(threadGroup, threadIndex) && (
                <div className="mt-4 text-center">
                  <button
                    onClick={() => showNewMessages(threadGroup, threadIndex)}
                    className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors duration-200"
                  >
                    {t('loadMore')} ({getUnreadMessageCount(threadGroup, threadIndex)})
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Load more button */}
      {hasMore && (
        <div className="p-6 bg-transparent border-t border-gray-200/60 rounded-b-lg">
          {lastLoadedCount > 0 && (
            <div className="mb-3 text-center text-sm text-green-600 font-medium animate-pulse">
              ✓ {t('newConversationsLoaded', { count: lastLoadedCount })}
            </div>
          )}
          <button
            onClick={handleLoadMore}
            disabled={loading}
            className={`w-full px-4 py-2 bg-[#667eea] text-white rounded-md hover:bg-[#5a67d8] focus:outline-none focus:ring-2 focus:ring-[#667eea] focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 ${loading ? 'animate-pulse' : ''}`}
          >
            {loading ? (
              <span className="flex items-center justify-center">
                <svg
                  className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                {t('loading')}
              </span>
            ) : (
              <span>{t('loadMore')} {loadMoreRangeText()}</span>
            )}
          </button>
        </div>
      )}
    </div>
  );
}
