// frontend/src/components/SearchBox.vue
<template>
  <div class="relative">
    <div class="relative">
      <input
        v-model="searchKeyword"
        type="text"
        :placeholder="$t('search.placeholder')"
        class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent text-sm"
        @input="handleSearch"
      />
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
        </svg>
      </div>
      <button
        v-if="searchKeyword"
        @click="clearSearch"
        class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
      >
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>

      <!-- 関連スレッド表示オプション（右上配置） -->
      <div v-if="searchKeyword" class="absolute -top-8 right-0">
        <label class="inline-flex items-center text-xs text-gray-600 bg-white px-2 py-1 rounded border border-gray-200 shadow-sm">
          <input
            type="checkbox"
            v-model="showRelatedThreads"
            @change="handleOptionsChange"
            class="mr-1 rounded border-gray-300 text-primary-500 focus:ring-primary-500 text-xs"
          />
          {{ $t('search.showRelatedThreads') }}
        </label>
      </div>
    </div>

    <!-- 検索結果サマリー -->
    <div v-if="searchKeyword && searchResults !== null" class="mt-2 text-sm text-gray-600">
      <span v-if="searchResults.total > 0">
        {{ $t('search.foundMessages', { keyword: searchKeyword, count: searchResults.total }) }}
      </span>
      <span v-else>
        {{ $t('search.noMessagesFound', { keyword: searchKeyword }) }}
      </span>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, defineEmits } from 'vue'

const emit = defineEmits(['search', 'clear', 'optionsChange'])

const searchKeyword = ref('')
const searchResults = ref(null)
const showRelatedThreads = ref(true) // デフォルトON

// デバウンス用のタイマー
let searchTimer = null

const handleSearch = () => {
  // 既存のタイマーをクリア
  if (searchTimer) {
    clearTimeout(searchTimer)
  }

  // 300ms後に検索実行
  searchTimer = setTimeout(() => {
    if (searchKeyword.value.trim()) {
      emit('search', {
        keyword: searchKeyword.value.trim(),
        showRelatedThreads: showRelatedThreads.value
      })
    } else {
      emit('clear')
      searchResults.value = null
    }
  }, 300)
}

const handleOptionsChange = () => {
  // オプション変更時にも検索を再実行
  if (searchKeyword.value.trim()) {
    emit('search', {
      keyword: searchKeyword.value.trim(),
      showRelatedThreads: showRelatedThreads.value
    })
  }
}

const clearSearch = () => {
  searchKeyword.value = ''
  searchResults.value = null
  emit('clear')
}

// 検索結果を受け取る
const setSearchResults = (results) => {
  searchResults.value = results
}

// 親コンポーネントから呼び出せるようにする
defineExpose({
  setSearchResults
})
</script>

// frontend-nextjs/components/SearchBox.tsx
'use client';

import { useState, useRef, useImperativeHandle, forwardRef, useCallback } from 'react';
import { useTranslations } from 'next-intl';

interface SearchBoxProps {
  onSearch?: (data: { keyword: string; showRelatedThreads: boolean }) => void;
  onClear?: () => void;
}

export interface SearchBoxHandle {
  setSearchResults: (results: { total: number; keyword: string } | null) => void;
  setSearchState: (keyword: string, showRelated: boolean) => void;
}

const SearchBox = forwardRef<SearchBoxHandle, SearchBoxProps>(
  ({ onSearch, onClear }, ref) => {
    const t = useTranslations('search');
    const [searchKeyword, setSearchKeyword] = useState('');
    const [searchResults, setSearchResults] = useState<{ total: number; keyword: string } | null>(null);
    const [showRelatedThreads, setShowRelatedThreads] = useState(true);
    const searchTimer = useRef<NodeJS.Timeout | null>(null);

    // Expose methods to parent component
    useImperativeHandle(ref, () => ({
      setSearchResults: (results: { total: number; keyword: string } | null) => {
        setSearchResults(results);
      },
      setSearchState: (keyword: string, showRelated: boolean) => {
        setSearchKeyword(keyword);
        setShowRelatedThreads(showRelated);
      },
    }));

    const handleSearch = useCallback((value: string) => {
      if (searchTimer.current) {
        clearTimeout(searchTimer.current);
      }

      // 300ms debounce
      searchTimer.current = setTimeout(() => {
        if (value.trim()) {
          onSearch?.({
            keyword: value.trim(),
            showRelatedThreads,
          });
        } else {
          onClear?.();
          setSearchResults(null);
        }
      }, 300);
    }, [onSearch, onClear, showRelatedThreads]);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = e.target.value;
      setSearchKeyword(value);
      handleSearch(value);
    };

    const clearSearch = () => {
      setSearchKeyword('');
      setSearchResults(null);
      if (searchTimer.current) {
        clearTimeout(searchTimer.current);
      }
      onClear?.();
    };

    const handleOptionsChange = () => {
      if (searchKeyword.trim()) {
        onSearch?.({
          keyword: searchKeyword.trim(),
          showRelatedThreads: !showRelatedThreads,
        });
      }
    };

    return (
      <div className="relative">
        {/* Show Related Threads Checkbox (positioned ABOVE input) */}
        {searchKeyword && (
          <div className="absolute -top-8 right-0 z-10">
            <label className="inline-flex items-center text-xs text-gray-600 bg-white px-2 py-1 rounded border border-gray-300 cursor-pointer">
              <input
                type="checkbox"
                checked={showRelatedThreads}
                onChange={(e) => {
                  setShowRelatedThreads(e.target.checked);
                  handleOptionsChange();
                }}
                className="mr-1"
              />
              {t('showRelatedThreads')}
            </label>
          </div>
        )}

        {/* Search Input Container */}
        <div className="relative">
          {/* Search Icon (left) */}
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg
              className="w-5 h-5 text-gray-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>

          {/* Search Input */}
          <input
            type="text"
            value={searchKeyword}
            onChange={handleInputChange}
            placeholder={t('placeholder')}
            className="w-full pl-10 pr-10 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500 placeholder:text-gray-600"
          />

          {/* Clear Button (right) */}
          {searchKeyword && (
            <button
              onClick={clearSearch}
              className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
              aria-label="Clear search"
            >
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          )}
        </div>

        {/* Search Results Summary */}
        {searchKeyword && searchResults !== null && (
          <div className="mt-2 text-sm text-gray-600">
            {searchResults.total > 0 ? (
              <span>
                {t('foundMessages', { keyword: searchResults.keyword, count: searchResults.total })}
              </span>
            ) : (
              <span>
                {t('noMessagesFound', { keyword: searchResults.keyword })}
              </span>
            )}
          </div>
        )}
      </div>
    );
  }
);

SearchBox.displayName = 'SearchBox';

export default SearchBox;
